export const PENDING_SYMBOLS = 'PENDING_SYMBOLS'
export const SUCCESS_SYMBOLS = 'SUCCESS_SYMBOLS'
export const FAILURE_SYMBOLS = 'FAILURE_SYMBOLS'
export const SET_SYMBOL = 'SET_SYMBOL'
export const SET_MARKET = 'SET_MARKET'

export const PENDING_CONTRACTS = 'PENDING_CONTRACTS'
export const SUCCESS_CONTRACTS = 'SUCCESS_CONTRACTS'
export const FAILURE_CONTRACTS = 'FAILURE_CONTRACTS'